repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.15
    hooks:
      - id: helmlint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
        additional_dependencies: [commitizen]
