name: Helm Charts Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm-chart-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Helm Dependencies
        run: |
          for dir in charts/*/; do
            if [ -f "${dir}Chart.yaml" ]; then
              helm dependency update "$dir"
            fi
          done

      - name: Package Helm Charts
        run: |
          mkdir -p .cr-release-packages
          for dir in charts/*/; do
            if [ -f "${dir}Chart.yaml" ]; then
              helm package "$dir" --destination .cr-release-packages/
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.CA_TOKEN }}
          CR_SKIP_EXISTING: true
          CR_GENERATE_RELEASE_NOTES: true

      # - name: Publish to JFrog Artifactory
      #   shell: bash
      #   run: |
      #     helm registry login nethermind.jfrog.io --username ${{ secrets.ARTIFACTORY_ANGKOR_USERNAME }} --password ${{ secrets.ARTIFACTORY_ANGKOR_TOKEN_DEVELOPER }}
      #     for chart in .cr-release-packages/*.tgz; do
      #       if [ -f "$chart" ]; then
      #         helm push "$chart" oci://nethermind.jfrog.io/angkor-helmoci-local
      #       fi
      #     done
